{"name": "test_get_orders_unauthorized_user", "status": "passed", "description": "Тест получения заказов для неавторизованного пользователя (ожидается ошибка 401)", "start": 1729799196421, "stop": 1729799197695, "uuid": "5569f8c0-f486-40bf-a314-fcc4aa37da5a", "historyId": "b2a22745f53fc627544557a2ebbefa75", "testCaseId": "b2a22745f53fc627544557a2ebbefa75", "fullName": "tests.test_append_orders_user#test_get_orders_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_append_orders_user"}, {"name": "host", "value": "falcon.local"}, {"name": "thread", "value": "44799-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_append_orders_user"}]}