{"name": "test_create_order_with_invalid_ingredients", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "access_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWE5ZTQyOWVkMjgwMDAxYjRmMWUxYSIsImlhdCI6MTcyOTc5OTM0MSwiZXhwIjoxNzI5ODAwNTQxfQ.XQfSWfMpv92wdQeaPp7SmuSCv7tqt51tnL8rxiWTQlg'\ninvalid_ingredients = ['invalid_hash']\n\n    def test_create_order_with_invalid_ingredients(access_token, invalid_ingredients):\n        \"\"\"Тест создания заказа с невалидным хешем ингредиента (ожидается ошибка 500)\"\"\"\n        headers_with_auth = {\n            \"Content-Type\": \"application/json\",\n            \"Authorization\": access_token\n        }\n        order_data = {\n            \"ingredients\": invalid_ingredients\n        }\n        response = requests.post(BASE_URL, json=order_data, headers=headers_with_auth)\n    \n        # Проверяем, что вернулась ошибка 500\n>       assert response.status_code == 500\nE       assert 400 == 500\nE        +  where 400 = <Response [400]>.status_code\n\ntests/test_create_order.py:90: AssertionError"}, "description": "Тест создания заказа с невалидным хешем ингредиента (ожидается ошибка 500)", "start": 1729799341116, "stop": 1729799341574, "uuid": "110d52b4-4df8-44d9-9121-09be9e524136", "historyId": "03357fa3cf18857b9f1050cf250c2a99", "testCaseId": "03357fa3cf18857b9f1050cf250c2a99", "fullName": "tests.test_create_order#test_create_order_with_invalid_ingredients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "host", "value": "falcon.local"}, {"name": "thread", "value": "44857-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}